from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='fifa-home'),
    path('about/', views.about, name='fifa-about'),
    path('cam/', views.camview, name='fifa-cam'),
    path('cb/', views.cbview, name='fifa-cb'),
    path('cdm/', views.cdmview, name='fifa-cdm'),
    path('cf/', views.cfview, name='fifa-cf'),
    path('cm/', views.cmview, name='fifa-cm'),
    path('gk/', views.gkview, name='fifa-gk'),
    path('lb/', views.lbview, name='fifa-lb'),
    path('lm/', views.lmview, name='fifa-lm'),
    path('lw/', views.lwview, name='fifa-lw'),
    path('lwb/', views.lwbview, name='fifa-lwb'),
    path('rb/', views.rbview, name='fifa-rb'),
    path('rm/', views.rmview, name='fifa-rm'),
    path('rw/', views.rwview, name='fifa-rw'),
    path('rwb/', views.rwbview, name='fifa-rwb'),
    path('st/', views.stview, name='fifa-st'),
    path('recommend/', views.recommend, name='fifa-recommend'),

    path(r'st/<int:playerid>', views.stplayerview, name='stprofile'),
    path(r'gk/<int:playerid>', views.gkplayerview, name='gkprofile'),
    path(r'cam/<int:playerid>', views.camplayerview, name='camprofile'),
    path(r'cb/<int:playerid>', views.cbplayerview, name='cbprofile'),
    path(r'cdm/<int:playerid>', views.cdmplayerview, name='cdmprofile'),
    path(r'cf/<int:playerid>', views.cfplayerview, name='cfprofile'),
    path(r'cm/<int:playerid>', views.cmplayerview, name='cmprofile'),
    path(r'lb/<int:playerid>', views.lbplayerview, name='lbprofile'),
    path(r'lm/<int:playerid>', views.lmplayerview, name='lmprofile'),
    path(r'lw/<int:playerid>', views.lwplayerview, name='lwprofile'),
    path(r'lwb/<int:playerid>', views.lwbplayerview, name='lwbprofile'),
    path(r'rb/<int:playerid>', views.rbplayerview, name='rbprofile'),
    path(r'rm/<int:playerid>', views.rmplayerview, name='rmprofile'),
    path(r'rw/<int:playerid>', views.rwplayerview, name='rwprofile'),
    path(r'rwb/<int:playerid>', views.rwbplayerview, name='rwbprofile'),
]