from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='fifa-home'),
    path('about/', views.about, name='fifa-about'),
    path('cam/', views.camview, name='fifa-cam'),
    path('cb/', views.cbview, name='fifa-cb'),
    path('cdm/', views.cdmview, name='fifa-cdm'),
    path('cf/', views.cfview, name='fifa-cf'),
    path('cm/', views.cmview, name='fifa-cm'),
    path('gk/', views.gkview, name='fifa-gk'),
    path('lb/', views.lbview, name='fifa-lb'),
    path('lm/', views.lmview, name='fifa-lm'),
    path('lw/', views.lwview, name='fifa-lw'),
    path('lwb/', views.lwbview, name='fifa-lwb'),
    path('rb/', views.rbview, name='fifa-rb'),
    path('rm/', views.rmview, name='fifa-rm'),
    path('rw/', views.rwview, name='fifa-rw'),
    path('rwb/', views.rwbview, name='fifa-rwb'),
    path('st/', views.stview, name='fifa-st'),

    path(r'st/(?P<playerid>\d+)/$', views.stplayerview, name='stprofile'),
    path(r'gk/(?P<playerid>\d+)/$', views.gkplayerview, name='gkprofile'),
    path(r'cam/(?P<playerid>\d+)/$', views.camplayerview, name='camprofile'),
    path(r'cb/(?P<playerid>\d+)/$', views.cbplayerview, name='cbprofile'),
    path(r'cdm/(?P<playerid>\d+)/$', views.cdmplayerview, name='cdmprofile'),
    path(r'cf/(?P<playerid>\d+)/$', views.cfplayerview, name='cfprofile'),
    path(r'cm/(?P<playerid>\d+)/$', views.cmplayerview, name='cmprofile'),
    path(r'lb/(?P<playerid>\d+)/$', views.lbplayerview, name='lbprofile'),
    path(r'lm/(?P<playerid>\d+)/$', views.lmplayerview, name='lmprofile'),
    path(r'lw/(?P<playerid>\d+)/$', views.lwplayerview, name='lwprofile'),
    path(r'lwb/(?P<playerid>\d+)/$', views.lwbplayerview, name='lwbprofile'),
    path(r'rb/(?P<playerid>\d+)/$', views.rbplayerview, name='rbprofile'),
    path(r'rm/(?P<playerid>\d+)/$', views.rmplayerview, name='rmprofile'),
    path(r'rw/(?P<playerid>\d+)/$', views.rwplayerview, name='rwprofile'),
    path(r'rwb/(?P<playerid>\d+)/$', views.rwbplayerview, name='rwbprofile'),
]