# Generated by Django 3.0.4 on 2020-03-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'cam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cb',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'cb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cdm',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'cdm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cf',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'cf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cm',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'cm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gk',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=2)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'gk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lb',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'lb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lm',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'lm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lw',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'lw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lwb',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'lwb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rb',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'rb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rm',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'rm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rw',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'rw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rwb',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'rwb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='St',
            fields=[
                ('sofifa_id', models.AutoField(db_column='sofifa_id', primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='short_name', max_length=50)),
                ('long_name', models.CharField(db_column='long_name', max_length=100)),
                ('age', models.IntegerField(db_column='age')),
                ('dob', models.DateField(db_column='dob')),
                ('nationality', models.CharField(db_column='nationality', max_length=25)),
                ('club', models.CharField(db_column='club', max_length=50)),
                ('player_positions', models.CharField(db_column='player_positions', max_length=20)),
                ('player_image', models.CharField(db_column='player_image', max_length=200)),
            ],
            options={
                'db_table': 'st',
                'managed': True,
            },
        ),
    ]
