# Generated by Django 3.0.4 on 2020-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('sofifa_id', models.IntegerField(db_column='sofifa_id')),
                ('position', models.CharField(db_column='player_position', max_length=3)),
                ('favorite', models.IntegerField(db_column='favorite')),
            ],
            options={
                'db_table': 'favorites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('sofifa_id', models.IntegerField(db_column='sofifa_id')),
                ('position', models.CharField(db_column='player_position', max_length=3)),
                ('rating', models.IntegerField(db_column='user_rating')),
            ],
            options={
                'db_table': 'ratings',
                'managed': True,
            },
        ),
    ]
